<Horario>:
    orientation: 'vertical'
    padding: 20
    spacing: 10
    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: None
        height: 200
        Label:
            id: horario_atual
            text: 'Relógio'
            font_size: '50sp'
            halign: 'center'
            valign: 'middle'
            size_hint: 1, 1
            text_size: self.size
            font_name: 'fonts/Digital-7.ttf'  # Ajuste o caminho conforme necessário
